/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "#e4e2de",
        "on-primary": "#ffffff",
        "primary": "#8e4e00",
        "on-secondary-fixed": "#002112",
        "on-surface-variant": "#534437",
        "secondary-fixed": "#93f7bf",
        "on-primary-fixed-variant": "#6c3a00",
        "on-error": "#ffffff",
        "on-surface": "#1b1c1a",
        "on-error-container": "#93000a",
        "tertiary": "#6d4ea2",
        "background": "#fbf9f5",
        "on-tertiary-fixed-variant": "#543589",
        "on-secondary-fixed-variant": "#005232",
        "on-tertiary-fixed": "#270058",
        "primary-fixed-dim": "#ffb778",
        "inverse-on-surface": "#f2f0ed",
        "surface-container-highest": "#e4e2de",
        "surface-container-lowest": "#ffffff",
        "error": "#ba1a1a",
        "outline-variant": "#d9c2b1",
        "surface-bright": "#fbf9f5",
        "surface-container-high": "#eae8e4",
        "secondary": "#006c44",
        "surface-container": "#efeeea",
        "primary-container": "#e8913a",
        "surface-container-low": "#f5f3ef",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#77daa4",
        "tertiary-fixed-dim": "#d4bbff",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#2e1500",
        "surface": "#fbf9f5",
        "on-tertiary-container": "#48287c",
        "on-secondary-container": "#007349",
        "outline": "#867465",
        "on-secondary": "#ffffff",
        "surface-tint": "#8e4e00",
        "inverse-primary": "#ffb778",
        "surface-dim": "#dbdad6",
        "tertiary-fixed": "#ebdcff",
        "primary-fixed": "#ffdcc1",
        "on-background": "#1b1c1a",
        "tertiary-container": "#b695f0",
        "secondary-container": "#93f7bf",
        "on-primary-container": "#5b3000",
        "inverse-surface": "#30312e",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      keyframes: {
        'pulse-glow': {
          '0%, 100%': { boxShadow: '0 0 8px rgba(232,145,58,0.3)' },
          '50%': { boxShadow: '0 0 20px rgba(232,145,58,0.6)' },
        },
        'slide-up': {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'count-up': {
          '0%': { transform: 'translateY(8px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        'shake': {
          '0%, 100%': { transform: 'translateX(0)' },
          '20%, 60%': { transform: 'translateX(-4px)' },
          '40%, 80%': { transform: 'translateX(4px)' },
        },
        'confetti-fall': {
          '0%': { transform: 'translateY(-10px) rotate(0deg)', opacity: '1' },
          '100%': { transform: 'translateY(100px) rotate(720deg)', opacity: '0' },
        },
      },
      animation: {
        'pulse-glow': 'pulse-glow 2s ease-in-out infinite',
        'slide-up': 'slide-up 0.4s ease-out',
        'fade-in': 'fade-in 0.3s ease-out',
        'count-up': 'count-up 0.4s ease-out',
        'shake': 'shake 0.5s ease-in-out',
        'confetti-fall': 'confetti-fall 1.5s ease-out forwards',
      },
    },
  },
  plugins: [],
}
